# Generated by Django 4.1.7 on 2023-03-24 10:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blob',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('blob', models.CharField(max_length=100, unique=True)),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Mention',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('rank', models.IntegerField()),
                ('mention', models.CharField(max_length=70)),
                ('position', models.IntegerField()),
                ('url', models.URLField()),
                ('blob_id', models.ForeignKey(db_column='blob_id', on_delete=django.db.models.deletion.CASCADE, to='getMentions.blob')),
            ],
        ),
        migrations.AddIndex(
            model_name='mention',
            index=models.Index(fields=['blob_id', 'rank'], name='getMentions_blob_id_2ce7ad_idx'),
        ),
    ]
