# Generated by Django 4.1.7 on 2023-03-24 14:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('getMentions', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mention',
            name='position',
        ),
    ]
