# Generated by Django 4.1.7 on 2023-03-25 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getMentions', '0002_remove_mention_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='mention',
            field=models.CharField(max_length=200),
        ),
    ]
