# Generated by Django 4.1.7 on 2023-03-25 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('getMentions', '0003_alter_mention_mention'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mention',
            name='mention',
            field=models.CharField(max_length=400),
        ),
    ]
